-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 23, 2024 at 07:57 PM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cms`
--

--
-- Dumping data for table `call_scripts`
--

INSERT INTO `call_scripts` (`id`, `call_id`, `department_id`, `script`, `extra_filter`, `deleted_at`, `created_at`, `updated_at`) VALUES
(1, 1, 1, 'Hello this is user_name calling from company_name may I speak to customer_name.</br></br>\nHello customer_name_1, I’m calling from the deal review department to confirm that we have received your\nproject in our system. I will be emailing you a review packet that will contain your contract and other\nagreements that you have signed with salespartner_name (Sales Partner Name)</br></br>\nPlease review all the documents attached in the email and confirm all the information is accurate. Once\nwe receive a response email from you, someone from our department will be in contact with you to\nfurther assist you with the rest of your project.</br></br>\nWhile I have you on the phone, did you have any questions regarding the recent solar agreement that you\nsigned with salespartner_name_1 ?</br></br>\n', '', NULL, '2024-06-23 09:09:29', '2024-06-23 09:09:29'),
(2, 2, 1, 'Hello this is user_name calling from company_name may I speak to customer_name.</br></br>\nHello customer_name_1, Thank you for returning the review packet to us in a timely manner. Upon doing a final\ncheck we were able to determine that your project is ready to be moved to our next department.</br>\nPlease expect a call from someone in our welcome call department where they will be helping you.</br></br>\nschedule your site assessment. The welcome call team will also help walk you through the process for the\nremainder of your solar project.</br></br>\nThank you so much for letting me review this information with you, and we look forward to providing you\nan exceptional experience for the coming weeks.</br></br>\nBefore I let you go, was there anything else that I am able to help you with?', '', NULL, '2024-06-23 09:09:29', '2024-06-23 09:09:29'),
(3, 1, 2, 'Hello this is user_name calling from company_name may I speak to customer_name.</br></br>\n        Hello customer_name_1, I want to start off this conversation by thanking you for choosing salespartner_name as\n        your solar provider.</br></br>\n        This is your official welcome call and while I have you on the phone I would like to schedule your site\n        survey assessment.</br></br>\n        To complete the site survey assessment we will need to send a site assessor to your home to take some\n        pictures and gather some data so we can create your site plan for your solar system. The assessment\n        should take around an hour to complete.</br></br>\n        Can you please tell me your next available date when I can send my assessor out to your home?</br></br>\n\n        Perfect, our site assessor will be there __________ between the hours of _____________.\n        Once our site assessor has gathered all the information he needs from the assessment you will receive a\n        phone call from our department confirming we have received all the data before we move your project to\n        our Engineering Department.</br></br>\n\nLastly, while I still have you on the phone can you please confirm if your home is a part of any\n        HomeOwner Association.<span style=\"color:red;font-weight:bold;\"> Note: If they are a part of an HOA, please input the name and number of the\n            HOA.</span>\n\n        Thank you for that information, is there anything else I can assist you with while I have you on the phone?', '', NULL, '2024-06-23 09:09:29', '2024-06-23 09:09:29'),
(4, 2, 2, ' Hello this is user_name calling from company_name may I speak to customer_name.</br></br>\r\nHello customer_name_1 I’m calling in regards to your site survey assessment to let you know we have received\r\nthe photos from our site assessor and have determined that your project is ready to be moved to our next\r\ndepartment.\r\nPlease expect a call from the Engineering Department in the next few days to let you know they have\r\nemailed you a preliminary site plan and to go over a few details regarding your project.\r\nIs there anything else I can assist you with while I have you on the phone?', '', NULL, '2024-06-23 09:09:29', '2024-06-23 09:09:29'),
(5, 1, 3, 'Hello this is user_name calling from company_name may I speak to customer_name.</br></br>\r\nHello customer_name_1 , I’m calling from the engineering department to let you know that your site plan is\r\nready for your approval and is waiting for you in your inbox. If you approve of the layout and\r\nequipment locations, please reply with \"Approved.\" If you have any questions or concerns regarding the\r\nsite plan please let us know within 48 hours. If we do not hear from you within those 48 hours, we will be\r\nmoving your project forward. I\'m looking forward to your response.\r\n</br></br>\r\nIs there anything else I can assist you with while I have you on the phone?', '', NULL, '2024-06-23 09:09:29', '2024-06-23 09:09:29'),
(6, 2, 3, 'Hello this is user_name calling from company_name may I speak to customer_name.</br></br>\r\nHello customer_name_1 , I’m calling in regards to your finalized plans to let you know we have them in hand and\r\nnow we are moving your project to our next department.\r\n</br></br>\r\nPlease expect a call from the Permit Department in the next few days to let you know they have received\r\nyour finalized engineered plans and for them to tell you when they will start the permit process for your\r\nproject.</br></br>\r\nIs there anything else I can assist you with while I have you on the phone?', '', NULL, '2024-06-23 09:09:29', '2024-06-23 09:09:29'),
(7, 1, 4, 'Hello this is user_name calling from company_name may I speak to customer_name.<br/><br/>\r\nHello customer_name_1, I’m calling from the Install department to let you know we have received your permit and that your project has been moved to our department and we have your job in our cue.\r\nWhile I have you on the phone I would love to schedule your solar installation date.<br/><br/>\r\nAre you available for an install on ____________________?<br/><br/>\r\nPerfect, I have you all set for ______________________. (If MPU is needed) It looks like we will be upgrading your Main Service Panel as well, are you available on _____________?<br/><br/>\r\nPlease be aware for the MPU, you may have a hole in your wall until we pass inspection which our\r\ninspection team will schedule.<br/><br/>\r\nThe Installation should take __________________. After we receive completion verification pictures from our Install team you should expect a call from our department to let you know that we have completed your Installation.<br/><br/>\r\nIs there anything else I can assist you with while I have you on the phone?', '', NULL, '2024-06-23 09:09:29', '2024-06-23 09:09:29'),
(8, 1, 4, 'Hello this is user_name calling from company_name may I speak to customer_name.<br/><br/>\r\nHello customer_name_1, I’m calling from the Install department to let you know we have received your permit and HOA (approval and/or Prelim approval) and that your project has been moved to our department and we have your job in our cue.<br/><br/>\r\nWhile I have you on the phone I would love to schedule your Install date.<br/><br/>\r\nAre you available for an install on ____________________?<br/><br/>\r\nPerfect, I have you all set for ______________________. (If MPU is needed) It looks like we will be upgrading your Main Service Panel as well, are you available on _____________?<br/><br/>\r\nPlease be aware for the MPU, you may have a hole in your wall until we pass inspection which our\r\ninspection team will schedule.<br/><br/>\r\nThe Installation should take __________________. After we receive completion verification pictures from our Install team you should expect a call from our department to let you know that we have completed your Installation.', 'hoa', NULL, '2024-06-23 09:09:29', '2024-06-23 09:09:29'),
(9, 2, 4, 'Hello this is user_name calling from company_name may I speak to customer_name.<br/><br/>\r\nHello customer_name_1 I’m calling in regards to your solar installation to let you know we have completed your installation along with your MPU and have received completion verification pictures from our Installers and we are moving your project to our next department.<br/><br/>\r\nPlease expect a call from the Inspection Department in the next few days to let you know when the\r\nInspection will be scheduled for your project.<br/><br/>\r\nIs there anything else I can assist you with while I have you on the phone?', '', NULL, '2024-06-23 09:09:29', '2024-06-23 09:09:29');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
